### ISSUE TITLE
"error" window poping up on startup.

### ISSUE THREAD

**Issue by kenfallon** [notklaatu/stopgo#41]
On opening the application the dialog box opens  "Stop! Open or Create new project first!". This is hardly an error as it is the first time we opened the application. 

It is inconvienient to have to click close each time the application is opened. 

As this is informational, it should be a toned down informational message in the application itself. Something along the lines of "Welcome to stopgo.  Please create a new project"

If it is a requirement to open a project, then a better approach would to be immediatly to open the fiel dialogue.

**Comment by notklaatu** [comment]
This is a feature specifically requested by UX designer @cyanidecupcake because we find that kids don't remember to start a project and *save* the project, rendering in random porjects being saved in default locations. In the classroom, this is problematic for the instructor when she goes round to the computers to gather up the class projects at the end of the day. 

That being said, I'll look into implementing a friendlier, less error-like message.

**Comment by notklaatu** [comment]
I've added an option in Preferences to skip the startprompt. The options are: 
* show prompt (default)
* show no prompt
This will be pushed to master "soon".
PUSHED 6ab1bd351c71fe2feb94a422fd3a8f1f2b54a254

Worth noting: 
If a project already exists, you can provide the path to your project in a terminal:
    $ /path/to/stopgo ~/path/to/project_folder/project_file
