### ISSUE TITLE
How did you handle image/video capture?

### ISSUE THREAD

**Issue by define-private-public** [notklaatu/stopgo#51]
Hi.

I'm currently working on my own animation tool.  It's intended for pencil tests, but it might be used as stop motion software as well.  Currently I've been planning to use libgphoto2 to handle the camera feed, but it's been quite difficult to work with.  I've seen that you're using libVLC to handle the camera stuffs.

Could you point me towards some tutorials or info that you used?  Because of how difficult it can be to work with libgphoto2, I've been looking at alternative methods of handling video/image capture.

Thanks,
~Ben

**Comment by notklaatu** [comment]
Hey Ben. I can't point you to a tutorial on the subject (yet) because I don't know of one. I just read the Python code of vlc.py and tried some stuff out.

I'll try to write a quick tutorial about it this weekend. Then I'll point you to it :-)

I'm happy to (try to) help, though, so don't hesitate to ask questions. Specifically, which part are you asking about? camera detection, taking the photo, onion-skinning? the whole thing?

**Comment by notklaatu** [comment]
No response in 3 months -> closing.

Feel free to reopen if you have further; questions.
